# Generated by Django 4.2.1 on 2023-05-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('snack', 'Snack'), ('hot_drink', 'Hot Drink'), ('cold_drink', 'Cold Drink')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
